# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
