# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweets_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='reply',
            field=models.BooleanField(default=False, verbose_name=b'Is a reply?'),
        ),
    ]
